export const languageData = [
  { label: "Hindi", value: "Hindi" },
  { label: "English", value: "English" },
  { label: "Bengali", value: "Bengali" },
  { label: "Punjabi", value: "Punjabi" },
  { label: "Urdu", value: "Urdu" },
  { label: "Marathi", value: "Marathi" },
  { label: "Telugu", value: "Telugu" },
  { label: "Tamil", value: "Tamil" },
  { label: "Gujarati", value: "Gujarati" },
  { label: "Kannada", value: "Kannada" },
  { label: "Odia", value: "Odia" },
  { label: "Malayalam", value: "Malayalam" },
  { label: "Assamese", value: "Assamese" },
  { label: "Sanskrit", value: "Sanskrit" },
  { label: "French", value: "French" },
  { label: "Spanish", value: "Spanish" },
  { label: "German", value: "German" },
  { label: "Mandarin", value: "Mandarin" },
  { label: "Japanese", value: "Japanese" },
  { label: "Russian", value: "Russian" },
  { label: "Italian", value: "Italian" },
  { label: "Korean", value: "Korean" },
  { label: "Indonesian", value: "Indonesian" },
  { label: "Arabic", value: "Arabic" },
  { label: "Portuguese", value: "Portuguese" },
];
